# How to use this plugin?
# It's simple

#############################################
#                  EXAMPLE                  #
#############################################
#commands:                                  #
#  <some-name>:                             #
#    executes: "say hi"                     #
#    description: "Some description"        #
#    aliases:                               #
#        - "greet-players"                  #
#        - "welcome-players"                #
#############################################

# Commands you define in "aliases" will execute command you defined "executes"

# Command "greet-player" will execute command "say hi"
# Same goes for command "welcome-players"

commands:
  test:
    executes: "say test"
    description: "This is a description"
    aliases:
      - "test1"
      - "test2"

# TODO: Implement execute
# execute:
#   test:
#     - "say test"
#     - "say test1"
